@api = http://localhost:3000/productos

GET {{api}}

### 
POST {{api}}
Content-Type: application/json

{
    "nombre": "lechuga",
    "descripcion": "aaaa",
    "id_categoria": 1
    }

###
GET {{api}}/56

###
DELETE {{api}}/56

###
PUT {{api}}/55
Content-Type: application/json

{
    "nombre": "laptop hp",
    "descripcion": "gaming",
    "id_categoria": 2
    }

###
GET {{api}}/?categoria=2